### ISSUE TITLE
codec 能不能单独拆出一个单独项目？

### ISSUE THREAD

**Issue by benjamin-yin001** [go-netty/go-netty#10]
编码和解码这块，不仅这个项目用，别的项目也可能需要。每个项目都维护一套编码解码代码，太浪费人力资源。我记得以前看过一个资料，说一个框架用了intel的SSE指令解析HTTP消息，效率大增。这种方案不应该被埋没在某一个项目的代码里。

netty这样的项目，其实可以拆成3个单独的项目。
一个就是transport，把各种TCP、UDP、UNIX、PIPE等所有的IPC，都抽象成一个文件流，对外提供统一接口。
一个是编码解码库，负责把字节流编码成消息结构体，或者反之。
还有一个就是类似责任链一样的通用消息处理框架，通过流转消息，完成业务逻辑。不仅仅是HTTP框架，也可以处理各种消息队列的消息。其实到业务处理这块，流程基本都一样。

以前一直有这种想法，但是并没有做。建议本项目组织人力尝试一下。

**Comment by limpo1989** [comment]
go-netty定位是核心库 **目标是提供一个稳定的可扩展的核心**，本身整合的通用codec和tcp transport可以满足大部分的常见需求，降低学习成本的同时也对如何扩展提供给了参考  

transport & codec 使用者可以按照自己的需求进行扩展，一些transport实现参考[go-netty-transport](https://github.com/go-netty/go-netty-transport)，预计将来将会独立一个go-netty-codec用于实现其他的通用编解码器

Transport 本身就是 io.ReadWriteCloser 的抽象，它可以是SOCKET也可以是消息队列，文件，或者任何你能想到的东西，甚至你可以为基于redis-list来抽象一个redis-transport

另：项目自身的codec完全可以自己建立一个公共的codec，所有项目引用这个codec就可以复用了

如果你有好的想法欢迎PR
