### ISSUE TITLE
客户端强制退出后分包代码还在死循环

### ISSUE THREAD

**Issue by xgene** [go-netty/go-netty#12]
如题： 客户端强制断开连接后分包代码还在死循环，我知道你的代码中是让读到EOF后panic，让其退出， 但是如果代码写的有bug，即使客户端强制断开， 分包的代码还在死循环，这部分控制能否由框架处理呢，框架兜底，起码客户端断开以后，退出分包程序

**Comment by limpo1989** [comment]
正常来讲只要你不在分包代码里面去recover，那么肯定是可以跳出去的才对, 你的用法有(伪)代码示例吗
