### ISSUE TITLE
可以连接Java版本的netty服务吗？

### ISSUE THREAD

**Issue by DaiZero** [go-netty/go-netty#13]
这个库可以连接Java版本的netty服务吗？Java版本的netty服务端用的协议是ProtoBuf3

**Comment by limpo1989** [comment]
可以的，只要协议编解码器上是一致的

**Comment by DaiZero** [comment]
有没有示例啊？

**Comment by limpo1989** [comment]
Go语言的例子在这里 [go-netty-samples](https://github.com/go-netty/go-netty-samples)  
与Java进行连接的例子暂时没有 不过可以看看这个问题 #8

**Comment by DaiZero** [comment]
好的，谢谢，我研究一下
