### ISSUE TITLE
老哥，你有个文件是不是命名错误了？

### ISSUE THREAD

**Issue by wanliofficial** [go-netty/go-netty#17]
![微信截图_20201113143346](https://user-images.githubusercontent.com/11154968/99036827-5fb9f080-25bd-11eb-9fcd-0a21ecd5890b.png)
如图，`utils/reder_test.go`正确文件名应该是`utils/reader_test.go`，是不是这样的？

**Comment by limpo1989** [comment]
是的错误了，多谢提醒，下次提交的时候修正
