### ISSUE TITLE
Any pr or issue of getty is welcome.

### ISSUE THREAD

**Issue by AlexStocks** [go-netty/go-netty#2]
![image](https://user-images.githubusercontent.com/7959374/69914061-bd236300-147a-11ea-800f-0f33e10174f3.png)

Hi friend, if u have any advice for getty( github.com/alexstocks/getty ) , pls submit a pr or issue. thx.

**Comment by limpo1989** [comment]
Sorry i didn't mean to offend you.
I read the code of getty. Getty is not flexible enough in protocol extension and message codec processing. For example, if you need to add new protocol support（like KCP）, you need to modify the core library, and asynchronous IO method is not a Go best practice.

**Comment by limpo1989** [comment]
The purpose of go-netty is to explore a network library that has the flexibility of netty without losing the characteristics of Go itself, and has highly optimized the efficiency of network transmission. For example, the encoding process before network transmission, go-netty does not allocate extra memory for splicing headers and payloads.
