### ISSUE TITLE
链接建立之后发送消息不成功

### ISSUE THREAD

**Issue by xiaohei88** [go-netty/go-netty#20]
c, err := bootstrap.Connect("127.0.0.1:6565", nil)
	if err != nil {
		fmt.Println(err)
	}
	c.Write([]byte("看好看好看好看好看"))

客户端发送不成功，但是客户端断了 消息就发送过去了。为什么是传字节，不能是message netty.Message 这种类型么？

**Comment by limpo1989** [comment]
```bootstrap.Connect``` 返回的Channel  不是用来发送对象用的，你应该注册自己的Handler 然后再 Handler 处理函数中捕获HandlerContext  然后调用其Write 函数发送对象，对象会经过你自己注册的Codec 编码成 []byte 调用Channel底层的Write 接口发送出去，参考这个tcp例子 [tcp_server](https://github.com/go-netty/go-netty-samples/blob/af390a556298f7ca2df71cf88d90a89f7e40b387/tcp_server/main.go#L74)

**Comment by limpo1989** [comment]
重新设计了Channel.Write接口，现在可以通过Channel的Write接口进行对象发送了，内部会经过编码器流程最终编码并发送
