### ISSUE TITLE
看源码，为啥项目里面没有日志输出呢？

### ISSUE THREAD

**Issue by beckbikang** [go-netty/go-netty#21]

**Comment by limpo1989** [comment]
核心部分代码比较简单，业务上的日志都是在自定义handler中自己输出就可以了

**Comment by beckbikang** [comment]
这不是个好方式吧，给日志设置级别，trace才打开就行。

网络编程既然都选择了golang，就不用担心性能。

网络开销是毫秒级别的。而且关闭日志的一次判断还是微秒级别以下的。

可维护可调式是很重要的啊

**Comment by limpo1989** [comment]
感谢反馈，目前代码结构比较简单，暂时不考虑添加日志，如果后续加入丰富的特性后会考虑加上
