### ISSUE TITLE
你好，请问如何优雅的关闭客户端连接，有什么属性能告诉读者该通道已经关闭了！

### ISSUE THREAD

**Issue by liedezhangqiu** [go-netty/go-netty#23]
你好，请问如何优雅的关闭客户端连接，有什么属性能告诉读者该通道已经关闭了！

**Comment by limpo1989** [comment]
检测Channel是否被关闭可以看看最新版本新增的API IsActive() bool
https://github.com/go-netty/go-netty/blob/68000ac9a2c64956b257e6dbfcc3c3c499d21ce2/channel.go#L40
优雅关闭应该从应用层来考虑，比如发送一个协议通知对方即将关闭

**Comment by liedezhangqiu** [comment]
我的目的是想立即丢弃没有得到验证的客户端的连接！谢谢了！

**Comment by limpo1989** [comment]
Channel.Close()
