### ISSUE TITLE
服务端常驻一段时间后，内存占用会缓慢爬升到一个很大的占用范围

### ISSUE THREAD

**Issue by liedezhangqiu** [go-netty/go-netty#24]
一晚上的连通性测试之后内存从开始的几M到今天早上的700M，我看了下代码基本上没有频繁制造垃圾的点，请作者帮忙关注下是不是我的个例！

**Comment by limpo1989** [comment]
参考 https://segmentfault.com/a/1190000016412013 抓一下内存Heap图看看内存都在哪里
