### ISSUE TITLE
有计划使用 Epoll 实现吗？

### ISSUE THREAD

**Issue by AmourLinux** [go-netty/go-netty#25]
```
// start write & read routines
func (c *channel) serveChannel() {
	c.wait.Add(1)
	go c.readLoop()
	go c.writeLoop()
	c.wait.Wait()
}
```

大致翻了 channel 和 transport 部分源码，如上，看起来依然是 conn-per-G 模型，貌似没有使用 Epoll？

**Comment by limpo1989** [comment]
目前没有采用多路复用的方式，之前也有考虑过接类似 [evio](https://github.com/tidwall/evio) 的多路复用库做transport实现，不过那样的话编解码部分就不能简单的采用同步io的方式来解码了，而且市面上很多传输层协议都选择兼容了标准库的net.Conn （例如kcp-go, quic） 这样看起来更像是符合Go的编程方式。

**Comment by AmourLinux** [comment]
目前的方式确实更加符合 Go 的设计，不过在海量高并发的场景下，IO 多路复用性能更胜一筹。
毕竟 Go程 成本随低，但不是没有 : ）

**Comment by limpo1989** [comment]
是的，除了在网关这个层面对处理海量并发有需求之外，其他业务服务器所需要处理的连接数并不是特别多，瓶颈也不会是网络部分，更多的是业务上的瓶颈先一步抵达
