### ISSUE TITLE
TCP收到数据后在哪里设置直接发送到业务处理器？

### ISSUE THREAD

**Issue by wanliofficial** [go-netty/go-netty#28]
在运行测试代码时，第一个处理器总要定义为如何去拆这个包，如果第一个处理器没有拆这个包，那么后续处理器的HandleRead方法就不会被触发，直到这个连接被断开，此时会执行所有处理器的HandleRead函数，此时会收到缓冲区的所有数据。

但是目前我的需求是框架收到数据，就立马发送到业务处理器，不管这一段数据是否完整，而不是缓存到缓冲区中。

那么业务代码该怎么写？能提供一个代码片段么？

**Comment by limpo1989** [comment]
设置第一个解码器为 VariableLengthCodec

**Comment by wanliofficial** [comment]
> 设置第一个解码器为 VariableLengthCodec

好的，我试试

**Comment by wanliofficial** [comment]
老哥，go-netty文档不全，要不你跟我讲讲go-netty的设计思路，我来帮你写文档？

**Comment by wanliofficial** [comment]
我打算把这个框架用到公司一个物联网平台上去，所以必须对这个框架有足够的了解。

**Comment by limpo1989** [comment]
Transport 传输层定义 封装各种底层(tcp/udp/ws/kcp)传输协议提供统一的行为

**Comment by wanliofficial** [comment]
嗯，这个明白，老哥代码写的很规范，看文件名也能猜出来大概，详细的就要看代码逻辑了。

只是老哥说的这些概念，对于一个没有接触过netty框架的人来说是陌生的，他们的含义是什么？有什么用？他们又是如何相互协作的？？？
