### ISSUE TITLE
ctx.Channel().ID()是一个递增的int64，可能存在隐患

### ISSUE THREAD

**Issue by wanliofficial** [go-netty/go-netty#29]
如题，隐患是，大量设备频繁断开与连接，这个自增ID是不会回收之前用过的数字，比如：设备A连接了netty，此时ID是1，设备A断开连接，下次再连接，ID就是2了。

大量设备重复连接，int64只能表示到21亿左右，恐怕也不太够用。

所以老哥设计这个ID字段时，为啥会用int64类型，而不是UUID或者雪花ID？？？

**Comment by limpo1989** [comment]
int64 能够表达的范围是 2^63 - 1  绰绰有余了
默认的实现是自增 
https://github.com/go-netty/go-netty/blob/68000ac9a2c64956b257e6dbfcc3c3c499d21ce2/options.go#L52
允许指定一个自定义生成器
https://github.com/go-netty/go-netty/blob/68000ac9a2c64956b257e6dbfcc3c3c499d21ce2/options.go#L69

**Comment by wanliofficial** [comment]
嗯，看错了，这个数确实很大
