### ISSUE TITLE
bug of delimiterCodec

### ISSUE THREAD

**Issue by cocktail18** [go-netty/go-netty#3]
### description
if  len(delimiterCodec.delimiter) > 1  
then delimiterCodec can not decode as expected

### for example 
```
delimiterCodec := DelimiterCodec(1024, "---", true)
var src = []byte("Hello---world")
delimiterCodec.HandleRead(ctx, bytes.NewReader(src))
```

### Improvement suggestions
1. use bytes.Index 
2. wrap message with ringbuff or other buff before decode

**Comment by limpo1989** [comment]
Thanks for the feedback, i will fix it
