### ISSUE TITLE
lengthFieldCodec 粘包的问题

### ISSUE THREAD

**Issue by lgphp** [go-netty/go-netty#32]
lengthFieldCodec 在解码的时候，如果收到消息的速度很快的发1000条消息，1毫秒一条，会有粘包问题的出现，不知道大家遇到过吗
	{"error": "Frame length too large, frameLength(542336370) > maxFrameLength(65535)"}

**Comment by lgphp** [comment]
同样的Java的Netty就没有这个问题

**Comment by lgphp** [comment]
需要自己实现粘包与半包的解码

**Comment by limpo1989** [comment]
最好能提供一个最简单的能复现的例子（我基于[tcp_server](https://github.com/go-netty/go-netty-samples/tree/master/tcp_server)的基础上测试并没有出现你说的问题）

**Comment by ArvinLovegood** [comment]
这个问题应该是应答的报文都加了这个报文的长度，LengthFieldCodec里面最后有个OutboundHandler=LengthFieldPrepender
