### ISSUE TITLE
Has any plan to support additional headers for the Transport?

### ISSUE THREAD

**Issue by chinkwing** [go-netty/go-netty#36]

**Comment by limpo1989** [comment]
Please provide more information about `additional headers`

**Comment by chinkwing** [comment]
eg. As webscoket Transport,we may expect send/receive additional information (as header) in the beginning of the connection.

**Comment by limpo1989** [comment]
See this commit: [e644815677eb31b2e645788d8ca4e78f1dd954ae](https://github.com/go-netty/go-netty-transport/commit/e644815677eb31b2e645788d8ca4e78f1dd954ae)

**Comment by chinkwing** [comment]
> See this commit: [e644815677eb31b2e645788d8ca4e78f1dd954ae](https://github.com/go-netty/go-netty-transport/commit/e644815677eb31b2e645788d8ca4e78f1dd954ae)

Firstly,Tanks!

In my opinion,this commit partial fix the problem. As client user,that's Okay,but how can server extract additional information?

**Comment by limpo1989** [comment]
Here's an example

https://github.com/go-netty/go-netty-samples/blob/0dc552fc89978490e2e8fa70d20793944c05bd68/chat_server/main.go#L64-L67
