### ISSUE TITLE
SSL是否支持

### ISSUE THREAD

**Issue by ryu-shen** [go-netty/go-netty#39]
请问下该框架是否有对SSL相关支持，类似netty的SslHandler

**Comment by limpo1989** [comment]
有传输层的实现：https://github.com/go-netty/go-netty-transport/tree/master/tls

**Comment by ryu-shen** [comment]
> 有传输层的实现：https://github.com/go-netty/go-netty-transport/tree/master/tls

好的，感谢，再次请问下，该框架是类似netty的reactor模式，我看框架介绍没有特别详细，类似框架gnet/netpoll，这些都是基于reacor思想开发的框架。

**Comment by limpo1989** [comment]
当前的实现不是reactor模式，是基于net包的同步模式

**Comment by ryu-shen** [comment]
> 当前的实现不是reactor模式，是基于net包的同步模式

好的，了解，后续可以是否reactor模式改造？毕竟性能更好

**Comment by limpo1989** [comment]
go-netty设计之初是想要结合netty的流水线思想 + Go协程编程模式来简化网络编程，如果回退到reactor模式，那就和传统的C++/Java 一样了（C++/Java 社区也有各种基于协程的改造版本来提升编程体验），如果不是用来做高性能网关，当前的模式是性能足够的
