### ISSUE TITLE
怎么获知连接已经断开了？又没有显示方法检查连接（ctx）已经断开的方法？

### ISSUE THREAD

**Issue by M1178475702** [go-netty/go-netty#4]

**Comment by limpo1989** [comment]
一般不需要主动去检查链接断开，只需要在自己的HandleInactive里面去处理 你自己想要处理的断开逻辑就可以了，万一需要主动检查也是在HandleInactive这个里面去加一个自定义标记给外部使用
文档因为API还没完全稳定还要再等等不过你可以先看看例子 https://github.com/go-netty/go-netty-samples

**Comment by limpo1989** [comment]
* ActiveHandler    连接建立时被调用
* InboundHandler 收取消息时被调用
* OutboundHandler 发出消息时被调用
* ExceptionHandler 发生异常时被调用
* InactiveHandler 连接关闭时被调用
* EventHandler 触发自定义事件被调用

大多数的逻辑只需要关注这几个Handler就可以了
