### ISSUE TITLE
有没有心跳检测的实现

### ISSUE THREAD

**Issue by YesPass** [go-netty/go-netty#43]

**Comment by limpo1989** [comment]
https://github.com/go-netty/go-netty/blob/master/handler.go#L208,L221

**Comment by limpo1989** [comment]
有一个比较简单的做法：在服务器添加一个ReadIdleHandler，然后在自定义处理器处理 ReadIdleEvent  事件，进行心跳超时检测，在客户端连接上添加一个 WriteIdleHandler ，并在自定义处理器上处理 WriteIdleEvent 事件，主动发出心跳包

**Comment by YesPass** [comment]
谢谢告知！！
