### ISSUE TITLE
建立连接时是否可以认证？

### ISSUE THREAD

**Issue by zhangliu-0** [go-netty/go-netty#45]
是否存在什么handle 可以实现在建立连接的时候进行客户端认证，不合法的客户端拒绝连接？

**Comment by limpo1989** [comment]
这个得看您采用的协议以及认证依据？比如指定IP白名单？亦或者客户端上传认证信息用于验证？具体得看需求，然后添加相关认证handler处理即可，不合法的使用ctx.Close() 关闭连接

**Comment by zhangliu-0** [comment]
协议tcp 建立连接后维持心跳，认证依据是客户端有token，现在问题是不知道该在建立连接的时候客户端如何带上token 以及服务端该如何拦截到token信息？还是说必须要建立连接成功后客户端发送token消息在进行认证，不合法再来关闭ctx呢？

**Comment by limpo1989** [comment]
是的，必须建立连接并且接收到客户端上传的token信息之后才可以判断连接是否合法，在此之前服务器无法得知是连接否合法
