### ISSUE TITLE
不维护了么

### ISSUE THREAD

**Issue by ZH-21000301** [go-netty/go-netty#46]
不维护了么？

**Comment by limpo1989** [comment]
有在维护，有遇到什么问题可以直接提出来

**Comment by ZH-21000301** [comment]
有继续做netty中的work和boss线程池的功能么？

**Comment by limpo1989** [comment]
`go-netty` 中并不需要`netty`中那样的线程池，因为其底层工作模型不一样，`go-netty` 没有选择采用异步事件机制来驱动，而是按照go net推荐的方式进行网络消息收发处理（每个连接2个协程分别出来读写操作），也就是说你可以在网络处理中编写阻塞代码。

如果你确实有并发处理消息的需求，可以在服务器中添加一个自己的消息处理器，并在中投递到你自己的线程池中处理。
