### ISSUE TITLE
bootstrap 启动websocket 如何读取header？

### ISSUE THREAD

**Issue by YesPass** [go-netty/go-netty#49]
现在又这样的需求
后端的websocket服务不直接暴露给前端。而是通过nginx代理。
nginx会在转发请求客户端真实ip以header 字段传递给后端服务
后端的websocket 服务如何获取真实客户端的ip 的 header ？
请问下如何做？

nginx 配置如下 ，如何获取X-Real-IP 这个字段呢？
# WebSocket代理
        location = ^~ /example {
            proxy_pass http://192.168.100.20:8080; #这里是http不是ws，不用怀疑，代理的ip和port写ws访问的实际地址
            proxy_http_version 1.1; #这里必须使用http 1.1
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
            proxy_set_header  Host $http_host;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header  X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

**Comment by limpo1989** [comment]
可以参考 `go-netty-ws` 项目 （基于go-netty） 
https://github.com/go-netty/go-netty-ws/blob/master/conn.go#L104

**Comment by limpo1989** [comment]
老版本的话可以通过下列方式
```go
if wsTransport, ok := ctx.Channel().Transport().(interface{ HttpRequest() *http.Request }); ok {
  handshakeReq := wsTransport.HttpRequest()
  fmt.Println("websocket header: ", handshakeReq.Header)
}
```

新版可以通过下列方式
```go
if handshakeHeader, ok := ctx.Channel().Transport().(interface{ Header() http.Header }); ok {
  fmt.Println("websocket header: ", handshakeHeader)
}
```

建议更新到新版，或者直接用 go-netty-ws 项目
