### ISSUE TITLE
[bug]关于lengthFieldCodec的initialBytesToStrip

### ISSUE THREAD

**Issue by M1178475702** [go-netty/go-netty#5]
我的应用层协议的header只有一个长度为4的长度字段，因此我的设置是这样的
![image](https://user-images.githubusercontent.com/42426867/70388201-73da9280-19e9-11ea-9777-103843eb3256.png)
因为这是我第一次用类netty的包（包括java的），initialBytesToStrip起初我并不知道是什么作用，因此我设置成了0.
起初他正常工作。
当我用java的netty写客户端的时候，问题发生了。
我对java的设置开始也是这样，initialBytesToStrip设置为0
![image](https://user-images.githubusercontent.com/42426867/70388203-8a80e980-19e9-11ea-8caf-196eab110288.png)
但是我发现我收到的包总是会包括header（前四个长度字节）
通过查看java的netty的源码，我发现了，当交给下一个handler时，
netty是将包的总长度减去initialBytesToStrip
因为我设置的是0，所以总是将包头也算了进去。
而您的代码中的实现是用包体的长度减去initialBytesToStrip，所以我设置成0反而成功了
java中的做法：
![image](https://user-images.githubusercontent.com/42426867/70388270-578b2580-19ea-11ea-94ec-f3ab4714c7ad.png)
这里是又将framelength（本来是包体的长度）还原成了整个frame的长度
![image](https://user-images.githubusercontent.com/42426867/70388272-5b1eac80-19ea-11ea-9797-a34838b1e49e.png)

**Comment by limpo1989** [comment]
感谢反馈
编解码器兼容的问题我会重新梳理，需要一些时间
