### ISSUE TITLE
Netty的LengthFieldBasedFrameDecoder不会参与Outbound

### ISSUE THREAD

**Issue by RTM945** [go-netty/go-netty#55]
本项目的LengthFieldCodec自带了一个OutboundHandler，发送数据时也会按配置打包数据，和java-netty的使用习惯有区别，能不能提供一个接口来禁用掉LengthFieldCodec自带的OutboundHandler？

**Comment by limpo1989** [comment]
你可以自己写一个 MyLengthFieldCodec 然后嵌套一下LengthFieldCodec，并覆盖默认的 OutboundHandler 实现：

```go
type MyLengthFieldCodec  struct {
   LengthFieldCodec
}

func(fc *MyLengthFieldCodec)  HandleWrite(ctx OutboundContext, message Message) {
   // 覆盖LengthFieldCodec的实现
   // 这里什么都不做直接交给下一个处理器
   ctx .HandleWrite(message)
}

```

**Comment by RTM945** [comment]
> 你可以自己写一个 MyLengthFieldCodec 然后嵌套一下LengthFieldCodec，并覆盖默认的 OutboundHandler 实现：
> 
> ```go
> type MyLengthFieldCodec  struct {
>    LengthFieldCodec
> }
> 
> func(fc *MyLengthFieldCodec)  HandleWrite(ctx OutboundContext, message Message) {
>    // 覆盖LengthFieldCodec的实现
>    // 这里什么都不做直接交给下一个处理器
>    ctx .HandleWrite(message)
> }
> ```

go mod方式下不能嵌套，因为lengthFieldCodec是私有的....

**Comment by limpo1989** [comment]
> 因为lengthFieldCodec是私有的

嵌套 codec.Codec 接口类型 一样的效果

```go
type MyLengthFieldCodec  struct {
   codec.Codec
}

var myCodec = &MyLengthFieldCodec  {Codec: frame.LengthFieldCodec(....) }
```

**Comment by RTM945** [comment]
成功了，感谢
