### ISSUE TITLE
当做HTTP文件服务器时出现OOM

### ISSUE THREAD

**Issue by prospelynn** [go-netty/go-netty#56]
当我使用HTTP SERVER的示例实现之后，当同时下载文件的请求过多时出现OOM。
文件大小500M左右，程序分配内存4G，请问怎么解决呢？

**Comment by limpo1989** [comment]
方便提供一下能复现的最小例子代吗

**Comment by prospelynn** [comment]
好的 感谢大佬

**Comment by limpo1989** [comment]
@prospelynn v1.6.7 提交了
