### ISSUE TITLE
[bug]客户端与服务器（几乎）同时断开连接时，异常的CPU占用

### ISSUE THREAD

**Issue by M1178475702** [go-netty/go-netty#6]
【我又来提交bug了】
我的程序是这样的，当客户端想要断开连接时，会先发送断开消息，然后主动断开连接（可互动使用java的netty实现）
当服务器（go-netty实现）收到断开消息时，服务器也会主动断开连接（我不清楚这个操作是应该的还是不应该的，我之前认为这个是无所谓的）。但是当服务器放调用conn.Close(nil)时，该函数会返回，但是却会导致异常的cpu占用（从几乎百分之0升到快百分之30）
当我只选择一方断开连接，这个是正常的。

**Comment by M1178475702** [comment]
补充下，经过测试，客户端不主动断开连接，只有服务器主动调用Close依然会导致高CPU占用，且客户端收不到连接断开的消息（似乎没断开？）

**Comment by limpo1989** [comment]
最好贴一下代码

**Comment by M1178475702** [comment]
目前表面的问题找出来了
我用的是之前的版本 go get github.com/go-netty/go-netty v0.0.0-**20191128**064703-04b38873dc4a
当我在服务端主动断开连接时cpu会异常占用
今天下了最新的版本（1212）后这个问题自然地消失了，不知道修复了什么（话说最新版的RunForever函数被删掉了啊=。=）
![image](https://user-images.githubusercontent.com/42426867/70962317-ace8c600-20bf-11ea-951f-f33140d9195c.png)

**Comment by limpo1989** [comment]
* 连接关闭这块最近有修改，统一了行为：主动关闭不会触发异常流程，被动关闭会触发异常流程
* 异常流程只会在 panic的时候被调用（Close不会触发）
* 正常只需要关注 HandleInactive 就可以，只要关闭就会触发，而不管是否主动或者被动
* RunForever 比较有侵入性，放到用户层去做更灵活了，可以参考例子

```go
func RunAsSignal(signals ...os.Signal) func(netty.Bootstrap) {
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, signals...)

	return func(bs netty.Bootstrap) {
		select {
		case <-bs.Context().Done():
		case <-sigChan:
		}
	}
}

netty.NewBootstrap().Action(RunAsSignal(os.Kill, os.Interrupt))
```

**Comment by M1178475702** [comment]
感谢=。=
所以旧版本出现这个问题的原因是主动关闭后会触发异常处理，然后开启了哪些死循环么？
方便的话可以告知一下相关源码在哪里么？昨晚翻了很久源码也没找到原因。Close函数都是正常返回的，所以没看到哪里有类似死循环的调用。

**Comment by limpo1989** [comment]
* 我新增了一个 netty.WaitSignal 方法，可以简单的使用  <code>netty.NewBootstrap().Action(netty.WaitSignal(os.Kill, os.Interrupt))</code>
* Close以调用链的形式传播所以当前的ctx产生的事件不会被当前的handler处理到
* 主要关注 channel.go 可以回退版本到之前的 版本在Goland里面点暂停，看看调用栈
