### ISSUE TITLE
new requirement:  support UDP

### ISSUE THREAD

**Issue by freeasbird** [go-netty/go-netty#7]
Please add pure UDP transport.
BTW, did you compare the performance of go-netty with netty?
Is there any way to set  SO_REUSEPORT socket option?
Maybe with this option and gorutine process, the performance will be better.

**Comment by limpo1989** [comment]
I don't know where is the usage scenario of Raw UDP transport?
Maybe what you need is a reliable UDP-based transport protocol. See here [KCP & QUIC](https://github.com/go-netty/go-netty-transport)

**Comment by limpo1989** [comment]
About SO_REUSEPORT I have planned to support

**Comment by freeasbird** [comment]
> I don't know where is the usage scenario of Raw UDP transport?
> Maybe what you need is a reliable UDP-based transport protocol. See here [KCP & QUIC](https://github.com/go-netty/go-netty-transport)
No reliability required in some cases. UDP is basic protocol, clear and simple. :)
We need this protocol for network traffic. KCP is too heavy, we also don't need encryption feature in QUIC. 
It's just a suggestion.  :))))

**Comment by freeasbird** [comment]
> I don't know where is the usage scenario of Raw UDP transport?
> Maybe what you need is a reliable UDP-based transport protocol. See here [KCP & QUIC](https://github.com/go-netty/go-netty-transport)
_______________
No reliability is required in some cases. UDP is basic protocol, clear and simple. :)
We need this protocol for network traffic. KCP is too heavy, we also don't need encryption feature in QUIC.
It's just a suggestion. :))))

**Comment by limpo1989** [comment]
@freeasbird simple UDP transport are supported
[https://github.com/go-netty/go-netty-transport/tree/master/udp](https://github.com/go-netty/go-netty-transport/tree/master/udp)

**Comment by freeasbird** [comment]
thank you :)
